Add snap implementation
canonical/charmed-mysql-snap pull request #1
Opened 2023-02-01 19:56 UTC by jardon

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
There was no snap implementation for charmed-mysql. 

* **What is the new behavior (if this is a feature change)?**
We will now publish and support charmed-mysql as a snap that has all of the components needed for the charm

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
N/A

2023-02-02 17:47 UTC, shayancanonical commented on snap/snapcraft.yaml
> +      - xtrabackup
since we are now creating a `charmed-mysql-snap`, should we be doing something (perhaps downloading from source) to ensure that versions are aligned?

2023-02-06 17:08 UTC, paulomach requested changes
Looks good, but I missed `mysql-shell` inclusion in the mix

2023-02-06 17:08 UTC, paulomach commented on snap/local/start_mysql_router.sh
> +# For security measures, daemons should not be run as sudo. Execute mongod as the non-sudo user: snap-daemon.
nit: `s/mongod/mysql-router`

2023-02-06 17:08 UTC, paulomach commented on hooks/configure
> +export CONFIG_DIR="${SNAP_COMMON}/mysql"
Add shell shebang

2023-02-07 01:12 UTC, taurus-forever approved these changes
Tnx! LGTM.

Q: are we planning to rename SNAP `mysql-server` to `charmed-mysql` (and hide it from being searchable on SNAP WEB?

2023-02-07 01:12 UTC, taurus-forever commented on snap/local/start_mysql_router.sh
> +# For security measures, daemons should not be run as sudo. Execute mysql as the non-sudo user: snap-daemon.
```suggestion
# For security measures, daemons should not be run as sudo. Execute mysqlrouter as the non-sudo user: snap-daemon.
```

2023-02-08 20:01 UTC, shayancanonical approved these changes
LGTM, but Alex's questions are still relevant in my opinion. Additionally, thoughts on waiting to merge this PR until the snap has been tested in the MySQL VM and MySQLRouter VM charms?

2023-02-08 20:41 UTC, paulomach approved these changes
lgtm

2023-02-08 20:41 UTC, paulomach approved these changes

2023-02-10 20:02 UTC, merged