Upload snapcraft logs if publish of snap fails
canonical/charmed-mysql-snap pull request #24
Opened 2023-05-01 10:23 UTC by shayancanonical

## Issue
We do not publish snapcraft logs when a publish of a snap fails.

## Solution
Publish snapcraft logs when a snap publish fails

2023-05-01 11:46 UTC, carlcsaposs-canonical requested changes

2023-05-01 11:46 UTC, carlcsaposs-canonical commented on .github/workflows/publish.yaml
> +          path: ~/.local/state/charmcraft/log/
update path

2023-05-08 11:37 UTC, shayancanonical commented on .github/workflows/publish.yaml
> +          path: ~/.local/state/charmcraft/log/
im not sure i quite understand the suggestion. update path to?

2023-05-08 12:14 UTC, carlcsaposs-canonical commented on .github/workflows/publish.yaml
> +          path: ~/.local/state/charmcraft/log/
Should it be `snapcraft`? not sure what the snapcraft log path is

2023-05-08 12:18 UTC, shayancanonical commented on .github/workflows/publish.yaml
> +          path: ~/.local/state/charmcraft/log/
addressed in [66c88c9](https://github.com/canonical/charmed-mysql-snap/pull/24/commits/66c88c99be67c8b36de056132c9bb60fe3ca0715)

2023-05-08 12:20 UTC, carlcsaposs-canonical approved these changes

2023-05-08 20:09 UTC, paulomach approved these changes

2023-05-15 12:11 UTC, merged